export const mcpMockData = {
  "audit": {
    "id": "mcp-legacy-audit-1",
    "companyName": "MCP Funds",
    "websiteUrl": "https://www.sealeze.com",
    "industry": "Finance",
    "primaryService": "SEO",
    "preparedBy": "Metamend",
    "reportStructure": {
      "executiveSummary": `
  <p class="mb-6">MCP Funds occupies a critical space in the financial sector, yet our audit reveals a significant disconnect between your institutional credibility and your digital footprint. Currently, <strong>structural technical barriers are impeding search engines</strong> from indexing your most valuable content correctly, while performance friction on mobile devices threatens to erode user trust before a lead can even begin their inquiry.</p>
  
  <img src="/audits/mcp-assets/mcp_page_10_img_2.png" class="w-full max-w-sm float-right ml-8 mb-6 border-4 border-white shadow-xl rounded" alt="Competitor Example" />

  <p class="mb-6">This audit categorizes the friction points holding you back, and the opportunities waiting to be claimed into <strong>3 distinct phases of the user journey</strong>:</p>

  <ul class="space-y-4 my-8 pl-4">
    <li class="flex gap-3"><span class="text-blue-600 font-bold">•</span> <div><strong>Awareness:</strong> Identifying the technical barriers - like missing rich results and inconsistent title - that render the brand invisible to high-intent searchers.</div></li>
    <li class="flex gap-3"><span class="text-blue-600 font-bold">•</span> <div><strong>Consideration:</strong> Highlighting where site performance, broken links, and confusing navigation erode the confidence of users who do arrive.</div></li>
    <li class="flex gap-3"><span class="text-blue-600 font-bold">•</span> <div><strong>Conversion:</strong> Friction points that slow action, along with opportunities to strengthen performance as search continues to evolve.</div></li>
  </ul>
  
  <p>By correcting these core architectural and performance issues, we can transform your website from a passive informational repository into a high-performance engine for lead generation and brand authority.</p>
`
    }
  },
  "findings": [
    {
      "id": "mcp-finding-1",
      "title": "Disjointed URL Structure",
      "rawNotes": "The current URLs do not follow a clear parent-child structure. Product and category pages sit in separate directories instead of being properly nested, breaking logical hierarchy.",
      "stage": "Discovery",
      "category": "Technical SEO",
      "severity": "Medium",
      "polishedTitle": "Disjointed URL Structure",
      "polishedSummary": "The site's URL hierarchy is unorganized and non-nested, hindering search engine crawlability.",
      "polishedBody": "<p>The current website URL structure lacks a logical parent-child hierarchy. Because product and category pages reside in separate directories rather than being properly nested, search engines struggle to understand the relationship between pages, which ultimately limits discoverability.</p>",
      "businessImpact": "Poor URL structure prevents search engines from indexing site hierarchy effectively, reducing organic ranking potential.",
      "recommendation": "Implement a standardized, nested directory structure for all product and category pages.",
      "imageUrl": "/audits/mcp-assets/mcp_page_4_img_1.png",
      "layoutType": "image-left"
    },
    {
      "id": "mcp-finding-2",
      "title": "Accidentally Indexed CMS Pages",
      "rawNotes": "Some pages appear to be automatically generated by the CMS and, although they should not be indexed, they remain publicly accessible, weakening brand credibility.",
      "stage": "Discovery",
      "category": "Technical SEO",
      "severity": "High",
      "polishedTitle": "Accidentally Indexed CMS Pages",
      "polishedSummary": "Unintended CMS-generated pages are being indexed, diluting domain authority and crawl value.",
      "polishedBody": "<p>Several automatically generated CMS pages are currently accessible and indexed by search engines. These pages act as 'hidden pollutants' that dilute your domain authority and weaken your brand's credibility in search results.</p>",
      "businessImpact": "Indexing low-quality, automated pages wastes crawl budget and negatively impacts the site's overall domain authority.",
      "recommendation": "Identify all non-essential CMS pages and apply 'noindex' tags or remove them from the public sitemap.",
      "imageUrl": "/audits/mcp-assets/mcp_page_5_img_1.png",
      "layoutType": "text-only"
    },
    {
      "id": "mcp-finding-3",
      "title": "Missing Structured Data",
      "rawNotes": "Product review markups are one of the only elements that visually stand out in search results. Without it, product pages miss the chance to visually differentiate.",
      "stage": "Discovery",
      "category": "Technical SEO",
      "severity": "Medium",
      "polishedTitle": "Missing Structured Data",
      "polishedSummary": "Lack of product review schema prevents the site from displaying rich results in search engines.",
      "polishedBody": "<p>Product pages are missing structured data, specifically review markups. Without these, your search results lack visual enhancements, causing them to blend in with competitors instead of capturing user attention.</p>",
      "businessImpact": "Missing rich snippets results in lower click-through rates (CTR) compared to competitors who display star ratings in search.",
      "recommendation": "Implement Product and Review Schema markup across all product and catalog pages.",
      "imageUrl": "/audits/mcp-assets/mcp_page_6_img_1.png",
      "layoutType": "image-left"
    },
    {
      "id": "mcp-finding-4",
      "title": "Critical Mobile Latency",
      "rawNotes": "Internal images are served offsite and not being properly accredited as a true digital asset. Large image files cause latency, breaking expected navigation patterns.",
      "stage": "Consideration",
      "category": "Performance",
      "severity": "High",
      "polishedTitle": "Critical Mobile Latency",
      "polishedSummary": "Large, unoptimized image assets are significantly slowing down mobile page load speeds.",
      "polishedBody": "<p>The site experiences performance issues due to large, unoptimized image assets being served from external sources. This creates friction for mobile users and makes the user experience feel unpolished and slow.</p>",
      "businessImpact": "High mobile latency leads to increased bounce rates, as users abandon pages that do not load immediately.",
      "recommendation": "Optimize all image assets, serve them locally from your CDN, and implement lazy loading.",
      "imageUrl": "/audits/mcp-assets/mcp_page_7_img_4.jpeg",
      "layoutType": "image-left"
    },
    {
      "id": "mcp-finding-5",
      "title": "Complex Contact Forms",
      "rawNotes": "Contact forms require a high number of mandatory fields, increasing effort at the exact moment users are ready to take action.",
      "stage": "Conversion",
      "category": "Conversion Rate Optimization",
      "severity": "High",
      "polishedTitle": "Complex Contact Forms",
      "polishedSummary": "Excessive form fields are creating unnecessary friction and reducing lead conversion rates.",
      "polishedBody": "<p>Current contact forms are overly complex, requiring too many mandatory fields. Research indicates that conversion rates decline as additional fields are added; ideally, forms should be kept as short as possible to minimize friction.</p>",
      "businessImpact": "Higher barrier to entry at the conversion stage causes potential customers to abandon the form entirely.",
      "recommendation": "Reduce the number of mandatory form fields to only the essential information needed to initiate a sales conversation.",
      "imageUrl": "/audits/mcp-assets/mcp_page_10_img_2.png",
      "layoutType": "text-only"
    }
  ]
};